
version: "0.0.1"
services:

  web:
    build: .
    command:  /bin/sh -c "rm -r -f go && go build . && ./go"
    volumes: 
      - .:/app
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: 'postgres:13.0-alpine'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 1234
        POSTGRES_DB: main_db

volumes:
  postgres_data: